---
title: "Engineering Locomizer data"
format: html
editor: visual
---

# Clear environment

```{r}
rm(list=ls())
```

# Libraries

```{r}
library(tidyverse)
library(sf)
```

# Set directory

```{r}
wd <- "/Volumes/rdm04/DEBIAS"
```

# Read data

```{r}
# read data at MSOA level
df_htw <- read_csv( paste0(wd, "/data/inputs/locomizer/cheng-et-al_sd/MSOA_county_home_work.gz") )
df_all <- read_csv( paste0(wd, "/data/inputs/locomizer/cheng-et-al_sd/msoa_ODs_allactivity.gz") )
df_hex <- read_csv( paste0(wd, "/data/inputs/locomizer/cheng-et-al_sd/hex_ODs_allactivity.gz") )

# read lookup msoa to lda
lookup <- read_csv( paste0(wd, "/data/inputs/geographies/lookup21ew/OA_to_LSOA_to_MSOA_to_LAD_Dec_2021_EW_V3.csv") ) %>% 
  select( c(MSOA21CD, MSOA21NM, LAD22CD, LAD22NM) ) %>% 
  distinct(MSOA21CD, .keep_all = TRUE)
  
```

# Use all activity

## Adding LAD codes

```{r}
df_lad_codes <- df_all %>%
  left_join(select(lookup, MSOA21CD, LAD22CD), by = join_by(o_msoa == MSOA21CD )) %>%
  rename(o_LAD22CD = LAD22CD) %>% 
  left_join(select(lookup, MSOA21CD, LAD22CD), by = join_by(d_msoa == MSOA21CD )) %>%
  rename(d_LAD22CD = LAD22CD)

```

## Aggregating to LAD flows


```{r}
lad_flows <- df_lad_codes %>%
  group_by(o_LAD22CD, d_LAD22CD) %>%
  summarise(trips = sum(num_trips, na.rm = TRUE), .groups = 'drop')
```



```{r}
write_csv(lad_flows, "/Volumes/rdm04/DEBIAS/data/outputs/mapp2/flows/lad/flow-origin-destination_lad.csv")
```

# Use home to work data

## Adding LAD codes

```{r}
df_lad_codes <- df_htw %>%
  left_join(select(lookup, MSOA21CD, LAD22CD), by = join_by(MSOA21CD_home == MSOA21CD )) %>%
  rename(home_LAD22CD = LAD22CD) %>%
  left_join(select(lookup, MSOA21CD, LAD22CD), by = join_by(MSOA21CD_work == MSOA21CD )) %>%
  rename(work_LAD22CD = LAD22CD)

```

## Aggregating to LAD flows

```{r}
lad_flows <- df_lad_codes %>%
  group_by(home_LAD22CD, work_LAD22CD) %>%
  summarise(trips = sum(count, na.rm = TRUE), .groups = 'drop')
```

```{r}
write_csv(lad_flows, "/Volumes/rdm04/DEBIAS/data/outputs/mapp2/flows/lad/flow-home-work_lad_htw.csv")
```
