---
title: "08_pw_home_location"
format: html
editor: visual
---

```{r}
# Load libraries
library(dplyr)       # For data manipulation
library(h3)          # For geospatial indexing
library(fs)          # For file operations
library(readr)       # For reading and writing CSV files
```


```{r}

# Define working directories
wd <- "/Volumes/rdm04/DEBIAS/data/inputs/pickwell/uk/raw"
wd_geocoded <- "/Volumes/rdm04/DEBIAS/data/inputs/pickwell/uk/geocoded-hex10"

# List all subfolders (dates)
date_folders <- dir_ls(wd, type = "directory")

# Loop through each date folder
for (date_folder in date_folders) {
  # Extract folder name
  date_name <- basename(date_folder)
  
  # Create corresponding output folder
  output_folder <- file.path(wd_geocoded, date_name)
  dir_create(output_folder)
  
  # List all .csv.gz files in the current folder
  csv_files <- dir_ls(date_folder, glob = "*.csv.gz")
  
  # Process each file
  for (csv_file in csv_files) {
    message("Processing: ", csv_file)
    
    # Read the CSV file
    df <- read.table(
      csv_file,
      header = TRUE,
      fill = TRUE,
      sep = "\t"
    )
    
    # Transform the data
    df_new <- df %>%
      mutate(
        hour = as.POSIXlt(as.POSIXct(timestamp, origin = "1970-01-01", tz = "GMT"))$hour,
        wday = as.POSIXlt(as.POSIXct(timestamp, origin = "1970-01-01", tz = "GMT"))$wday,
        day = format(as.POSIXlt(timestamp, origin = "1970-01-01", tz = "GMT"), "%Y-%m-%d"),
        code_h3 = geo_to_h3(df[, c("latitude", "longitude")], 10)  # Apply geo_to_h3 function
      )
    
    # Define output file name
    file_name <- paste0(tools::file_path_sans_ext(basename(csv_file)), "-geocoded.csv.gz")
    output_path <- file.path(output_folder, file_name)
    
    # Save the transformed data
    write_csv(df_new, output_path)
  }
}

```


