---
title: "Analysing home location"
format: html
editor: visual
---

# Clean environment
```{r}
rm(list=ls())
```

# Libraries
```{r}
library(tidyverse)
library(sf)
library(h3)
```

# Read data
```{r}
df_home_location <- read_csv("/Volumes/DEBIAS/data/inputs/pickwell/uk/home-location/part-00000-22616738-1d83-45b0-9be8-2b01fc18da31-c000.csv")

sdf <- st_read("/Volumes/DEBIAS/data/inputs/geographies/boundaries/LAD_Dec_2021_GB_BFC_2022_simplified.gpkg") %>% 
  st_transform(crs = 4326)

head(df_home_location)
```

```{r}
# Create the histogram
ggplot(df_home_location, aes(x = percent)) +
  geom_histogram(fill = "skyblue", color = "black", bins = 50) +
  labs(title = "Histogram of Percent", x = "Percent", y = "Frequency") +
  theme_minimal()
```
```{r}
unique_vec <- unique(df_home_location$device_aid)
```


```{r}
coordinates <- h3_to_geo(df_home_location$location) %>% as_data_frame()
sdf_home_location <- cbind(df_home_location, coordinates) %>% 
  st_as_sf( coords = c("lng", "lat") , crs = 4326)

sdf_hex3 <- st_join(sdf, 
                    sdf_home_location,
                    join = st_contains) 

sdf_lda <- sdf_hex3 %>% 
  group_by(code) %>% 
  summarise( home_location_count = n( ))

st_write(sdf_lda, "/Volumes/DEBIAS/data/outputs/pw/home-locations/hex/home-location-count_lda.shp")
```

