---
title: "Engineering Locomizer data"
format: html
editor: visual
---

# Clear environment

```{r}
rm(list=ls())
```

# Libraries

```{r}
library(tidyverse)
library(sf)
```

# Set directory

```{r}
wd <- "/Volumes/rdm04/DEBIAS"
```

# Read data

```{r}
# read data at MSOA level
df_htw <- read_csv( paste0(wd, "/data/inputs/locomizer/cheng-et-al_sd/MSOA_county_home_work.gz") )
df_all <- read_csv( paste0(wd, "/data/inputs/locomizer/cheng-et-al_sd/msoa_ODs_allactivity.gz") )
df_hex <- read_csv( paste0(wd, "/data/inputs/locomizer/cheng-et-al_sd/hex_ODs_allactivity.gz") )

# read lookup msoa to lda
lookup <- read_csv( paste0(wd, "/data/inputs/geographies/lookup21ew/OA_to_LSOA_to_MSOA_to_LAD_Dec_2021_EW_V3.csv") ) %>% 
  select( c(MSOA21CD, MSOA21NM, LAD22CD, LAD22NM) ) %>% 
  distinct(MSOA21CD, .keep_all = TRUE)
  
```

# Use all activity

## Adding LAD codes

```{r}
df_lda_codes <- left_join(df_all, lookup, by = join_by(o_msoa == MSOA21CD ))
```

## Aggregating to LAD counts

```{r}
pop_count <- df_lda_codes %>% 
  group_by(LAD22CD) %>% 
  summarise( pop_dfd = sum(num_trips) )
```

```{r}
write_csv(pop_count, "/Volumes/rdm04/DEBIAS/data/outputs/mapp2/locations-origin/lad/location-origin-count_lad.csv")
```

# Use home to work data

## Adding LAD codes

```{r}
df_lda_codes <- left_join(df_htw, lookup, by = join_by(MSOA21CD_home == MSOA21CD ))
```

## Aggregating to LAD counts

```{r}
pop_count <- df_lda_codes %>% 
  group_by(LAD22CD) %>% 
  summarise( pop_dfd = sum(count) )
```

```{r}
write_csv(pop_count, "/Volumes/rdm04/DEBIAS/data/outputs/mapp2/locations-origin/lad/location-home-count_lad_htw.csv")
```
