---
title: "Engineering Locomizer data"
format: html
editor: visual
---

# Clear environment

```{r}
rm(list=ls())
```

# Libraries

```{r}
library(tidyverse)
library(sf)
```

# Set directory

```{r}
wd <- "/Volumes/DEBIAS"
```

# Read data

```{r}
# read data at MSOA level
df_htw <- read_csv( paste0(wd, "/data/inputs/locomizer/cheng-et-al_sd/MSOA_county_home_work.gz") )
df_all <- read_csv( paste0(wd, "/data/inputs/locomizer/cheng-et-al_sd/msoa_ODs_allactivity.gz") )
df_hex <- read_csv( paste0(wd, "/data/inputs/locomizer/cheng-et-al_sd/hex_ODs_allactivity.gz") )
```

# Use all activity

```{r}
pop_count <- df_all %>% 
  group_by(o_msoa) %>% 
  summarise( pop_dfd = sum(num_trips) ) %>%
  rename(MSOA21CD = o_msoa)
```

```{r}
write_csv(pop_count, "/Volumes/DEBIAS/data/inputs/mapp2/locations-origin/msoa/location-origin-count_msoa.csv")
```

# Use home to work data

```{r}
pop_count <- df_htw %>% 
  select(MSOA21CD_home, MSOA21CD_work, count) %>%
  group_by(MSOA21CD_home) %>% 
  summarise( pop_dfd = sum(count) ) %>%
  rename(MSOA21CD = MSOA21CD_home)
```

```{r}
write_csv(pop_count, "/Volumes/DEBIAS/data/inputs/mapp2/locations-origin/msoa/location-home-count_msoa_htw.csv")
```
